@startuml
hide empty description
[*] --> 作业压缩包文件打开
作业压缩包文件打开: do: 解压压缩包
作业压缩包文件打开 --> 作业压缩包文件关闭
作业压缩包文件关闭: do: 压缩包对象关闭

作业压缩包文件关闭 --> 学生作业开始过滤
学生作业开始过滤: do: 过滤多余的文件和文件夹
学生作业开始过滤 --> 学生作业过滤结束
学生作业过滤结束 --> [*]

@enduml
